name: Lint
on:
  workflow_call:
    inputs:
      NODE_VERSION:
        type: string
jobs:
  lint:
    runs-on: self-hosted
    container: node:${{ inputs.NODE_VERSION }}
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: yarn run eslint . --ext .js -c .eslintrc.js  #To display output on console
    - name: Generate Report
      run: yarn run eslint . --ext .js -c .eslintrc.js -f checkstyle > eslint.xml #To create report which will be use by checkstyle plugin
