---
name: Shared Workflow for actions
on :
  workflow_call:
    inputs:
      run_lint:
        default: 'false'
        type: string
      run_unit:
        default: 'false'
        type: string
      run_sonar:
        default: 'false'
        type: string
      NODE_VERSION:
        default: '16.15'
        type: string
      WORKING_DIRECTORY:
        default: ''
        type: string
    secrets:
          SONAR_TOKEN:
            required: false
          SONAR_HOST_URL:
            required: false
          SIMPPLR_NPM_TOKEN:
            required: false
jobs:
  shared-library-workflows-lint:
    if: ${{ inputs.run_lint == 'true' }}
    uses: Simpplr/github-shared-library/.github/workflows/lint.yaml@main
    with:
      NODE_VERSION: ${{ inputs.NODE_VERSION }}
  shared-library-workflows-unit-test:
    if: ${{ inputs.run_unit == 'true' }}
    uses: Simpplr/github-shared-library/.github/workflows/unit-test.yaml@main
    with:
      NODE_VERSION: ${{ inputs.NODE_VERSION }}
      WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
    secrets:
      SIMPPLR_NPM_TOKEN: ${{secrets.SIMPPLR_NPM_TOKEN}}
  shared-library-workflows-sonarqube:
    if: ${{ inputs.run_sonar == 'true' }}
    uses: Simpplr/github-shared-library/.github/workflows/sonarqube.yaml@main
    secrets:
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
      SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}
