name: Sonarqube
on:
  workflow_call:
jobs:
  run-sonarqube:
    runs-on: self-hosted
    container: ubuntu:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Sonarqube
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
