name: Unit Test
on:
  workflow_call:
    inputs:
      NODE_VERSION:
        type: string
      WORKING_DIRECTORY:
        type: string
    secrets:
      SIMPPLR_NPM_TOKEN:
        required: true
jobs:
  unit-test:
    runs-on: self-hosted
    container: ubuntu:latest
    steps:
    - uses: actions/checkout@v3
    - name: Import environment variables from a file
      id: import-env
      uses: actions/github-script@v6
      with:
        script: |
          const env = parseEnv(`${process.env.GITHUB_WORKSPACE}/dev.env`);
          Object.entries(env).forEach(x => core.exportVariable(...x)); // current job-level env
          return env;
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.NODE_VERSION }}
    - name: Install Modules
      working-directory: ${{ inputs.WORKING_DIRECTORY }}
      run: npm --version && npm install
      env:
        SIMPPLR_NPM_TOKEN: ${{ secrets.SIMPPLR_NPM_TOKEN }}     
    - name: Running unit test
      working-directory: ${{ inputs.WORKING_DIRECTORY }}
      run: npm run test
      env: ${{ fromJson(steps.import-env.outputs.result) }}
