name: Unit Test
on:
  workflow_call:
    inputs:
      NODE_VERSION:
        type: string
      WORKING_DIRECTORY:
        type: string
    secrets:
      SIMPPLR_NPM_TOKEN:
        required: true
jobs:
  unit-test:
    runs-on: self-hosted
    container: ubuntu:latest
    steps:
    - uses: actions/checkout@v3
    - name: Import environment variables from a file
      id: import-env
      shell: bash
      run: |
        cd .github/workflows && cat ${{ ut.env }} >> $GITHUB_ENV && return $GITHUB_ENV;
    - name: Print environment variable
      run: echo $USE_SINGLE_CLIENT
      env: ${{ steps.import-env.outputs.result }} # step-level env
    # - uses: actions/setup-node@v3
    #   with:
    #     node-version: ${{ inputs.NODE_VERSION }}
    # - name: Install Modules
    #   working-directory: ${{ inputs.WORKING_DIRECTORY }}
    #   run: npm --version && npm install
    #   env:
    #     SIMPPLR_NPM_TOKEN: ${{ secrets.SIMPPLR_NPM_TOKEN }}     
    # - name: Running unit test
    #   working-directory: ${{ inputs.WORKING_DIRECTORY }}
    #   run: npm run test
    #   env: ${{ fromJson(steps.import-env.outputs.result) }}
