name: Unit Test
on:
  workflow_call:
    inputs:
      NODE_VERSION:
        type: string
      WORKING_DIRECTORY:
        type: string
    secrets:
      SIMPPLR_NPM_TOKEN:
        required: true
jobs:
  unit-test:
    runs-on: self-hosted
    container: ubuntu:latest
    steps:
    - uses: actions/checkout@v3
    # - name: Import environment variables from a file
    #   id: import-env
    #   shell: bash
    #   run: |
    #     cd .github/workflows &&
    #     while read line; do
    #       echo "$line" >> $GITHUB_ENV
    #     done < ut.env
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.NODE_VERSION }}
    - name: Install Modules
      working-directory: ${{ inputs.WORKING_DIRECTORY }}
      run: npm --version && npm install
      env:
        SIMPPLR_NPM_TOKEN: ${{ secrets.SIMPPLR_NPM_TOKEN }}     
    - name: Running unit test
      working-directory: ${{ inputs.WORKING_DIRECTORY }}
      run: npm run test
      env:
          USE_SINGLE_CLIENT: 'Y'
          DEFAULT_IDLE_TIMEOUT_IN_MINS: 'NA'
          MAX_DELEGATION_REQUEST_DURATION_IN_SECS: '7200'
          IDP_ENCRYPTION_CERT: 'TESTCERT'
          ENV: 'DEV'
          NODE_ENV: 'DEV'
          PORT: '5000'
          DB_DIALECT: 'postgres' 
          ZEUS_DB_NAME: content_mgmt
