name: Unit Test
on:
  workflow_call:
    inputs:
      NODE_VERSION:
        type: string
      WORKING_DIRECTORY:
        type: string
    secrets:
      SIMPPLR_NPM_TOKEN:
        required: true
jobs:
  unit-test:
    runs-on: self-hosted
    container: ubuntu:latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.NODE_VERSION }}
    - name: Install Modules
      run: npm --version && npm install
      env:
        SIMPPLR_NPM_TOKEN: ${{ secrets.SIMPPLR_NPM_TOKEN }}
      with:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}      
    - name: Running unit test
      run: npm run test
      with:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}     
